# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulates the model when it is written as a R function
#' @export
cvode_R <- function(times, states, parameters, forcings_data, settings, model, jacobian) {
    .Call('RcppSundials_cvode_R', PACKAGE = 'RcppSundials', times, states, parameters, forcings_data, settings, model, jacobian)
}

#' Simulates the model when it is written as a C++ function using stl containers
#' @export
cvode_Cpp_stl <- function(times, states_, parameters_, forcings_data_, settings, model_, jacobian_) {
    .Call('RcppSundials_cvode_Cpp_stl', PACKAGE = 'RcppSundials', times, states_, parameters_, forcings_data_, settings, model_, jacobian_)
}

#' An example of model (unit test)
#' @export
example_model <- function(t, states, parameters, forcings) {
    .Call('RcppSundials_example_model', PACKAGE = 'RcppSundials', t, states, parameters, forcings)
}

#' An example of a model's Jacobian matrix (unit test)
#' @export
example_jacobian <- function(t, states, parameters, forcings) {
    .Call('RcppSundials_example_jacobian', PACKAGE = 'RcppSundials', t, states, parameters, forcings)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('RcppSundials_RcppExport_registerCCallable', PACKAGE = 'RcppSundials')
})
